# Name Space Creation
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-stack
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-stack
---
apiVersion: v1
kind: Namespace
metadata:
  name: pgadmin-stack
---
# Service Account Creation
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-sa
  namespace: grafana-stack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-sa
  namespace: postgres-stack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-sa
  namespace: pgadmin-stack
---
# Secret Provider Storage Class
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secrets
  namespace: postgres-stack
spec:
  provider: aws
  parameters:
    region: eu-central-1
    objects: |
      - objectName: "PostgresAdminPasswordSecret"
        objectType: "secretsmanager"
        objectAlias: "password"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-secrets
  namespace: grafana-stack
spec:
  provider: aws
  parameters:
    region: eu-central-1
    objects: |
      - objectName: "GrafanaAdminPasswordSecret"
        objectType: "secretsmanager"
        objectAlias: "admin-password"
      - objectName: "AzureClientIdSecret"
        objectType: "secretsmanager"
        objectAlias: "azure-client-id"
      - objectName: "AzureClientSecretSecret"
        objectType: "secretsmanager"
        objectAlias: "azure-client-secret"
      - objectName: "AzureTenantIdSecret"
        objectType: "secretsmanager"
        objectAlias: "azure-tenant-id"
      - objectName: "ALBDnsNameSecret"
        objectType: "secretsmanager"
        objectAlias: "alb-dns-name"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pgadmin-secrets
  namespace: pgadmin-stack
spec:
  provider: aws
  parameters:
    region: eu-central-1
    objects: |
      - objectName: "PgAdminEmailSecret"
        objectType: "secretsmanager"
        objectAlias: "email"
      - objectName: "PgAdminPasswordSecret"
        objectType: "secretsmanager"
        objectAlias: "password"
---
# Storage Class (EFS)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-xxxxxxxxx  # Replace with EFS ID
  directoryPerms: "700"
  uid: "999"
  gid: "999"
---
# Persistent Volumn Claim for Grafana & Postgres
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: postgres-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: grafana-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
# Postgres Deployment, Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres-stack
  labels:
    app: postgres
    name: postgres
    tier: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: secrets-store-sa
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsNonRoot: true
      containers:
      - name: postgres
        image: postgres:17.6
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: amazon_connect
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD_FILE
          value: /mnt/secrets-store/password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: secrets-store
          mountPath: /mnt/secrets-store
          readOnly: true
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: postgres-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-stack
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
# Grafana Deployment, Service and Ingress
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana-stack
  labels:
    app: grafana
    name: grafana
    tier: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: secrets-store-sa
      restartPolicy: Always
      automountServiceAccountToken: true
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        command: ["/bin/sh", "-c"]
        args:
          - |
            TENANT_ID=$(cat /mnt/secrets-store/azure-tenant-id)
            export GF_AUTH_AZUREAD_AUTH_URL="https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/authorize"
            export GF_AUTH_AZUREAD_TOKEN_URL="https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token"
            exec /run.sh
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD__FILE
          value: /mnt/secrets-store/admin-password
        - name: GF_AUTH_AZUREAD_ENABLED
          value: "true"
        - name: GF_AUTH_AZUREAD_NAME
          value: "SSO"
        - name: GF_AUTH_AZUREAD_CLIENT_ID__FILE
          value: /mnt/secrets-store/azure-client-id
        - name: GF_AUTH_AZUREAD_CLIENT_SECRET__FILE
          value: /mnt/secrets-store/azure-client-secret
        - name: GF_AUTH_AZUREAD_TENANT_ID__FILE
          value: /mnt/secrets-store/azure-tenant-id
        - name: GF_SERVER_ROOT_URL
          value: https://ALB_PLACE_HOLDER
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: secrets-store
          mountPath: /mnt/secrets-store
          readOnly: true
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: grafana-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana-stack
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: grafana-stack
  finalizers: []
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:149050210537:certificate/ba4441ea-5598-4679-942b-4aaf49aa2499
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
---
# PgAdmin Deployment, Service and Ingress
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: pgadmin-stack
  labels:
    app: pgadmin
    name: pgadmin
    tier: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      serviceAccountName: secrets-store-sa
      automountServiceAccountToken: true
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "$(cat /mnt/secrets-store/email)"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "$(cat /mnt/secrets-store/password)"
        command: ["/bin/sh", "-c"]
        args:
          - |
            export PGADMIN_DEFAULT_EMAIL=$(cat /mnt/secrets-store/email)
            export PGADMIN_DEFAULT_PASSWORD=$(cat /mnt/secrets-store/password)
            exec /entrypoint.sh
        volumeMounts:
        - name: secrets-store
          mountPath: /mnt/secrets-store
          readOnly: true
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: pgadmin-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: pgadmin-stack
spec:
  selector:
    app: pgadmin
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin
  namespace: pgadmin-stack
  finalizers: []
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:149050210537:certificate/ba4441ea-5598-4679-942b-4aaf49aa2499
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 8080}]'
    alb.ingress.kubernetes.io/ssl-redirect: '8080'
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin
            port:
              number: 80