# Service Account Creation
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-sa
  namespace: grafana-stack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-sa
  namespace: postgres-stack
---
# PgAdmin Service Account (COMMENTED - Not deployed)
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: secrets-store-sa
#   namespace: pgadmin-stack