# Secret Provider Storage Class
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secrets
  namespace: postgres-stack
spec:
  provider: aws
  parameters:
    region: eu-central-1
    objects: |
      - objectName: "PostgresAdminPasswordSecret"
        objectType: "secretsmanager"
        objectAlias: "password"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-secrets
  namespace: grafana-stack
spec:
  provider: aws
  parameters:
    region: eu-central-1
    objects: |
      - objectName: "GrafanaAdminPasswordSecret"
        objectType: "secretsmanager"
        objectAlias: "admin-password"
      - objectName: "AzureClientIdSecret"
        objectType: "secretsmanager"
        objectAlias: "azure-client-id"
      - objectName: "AzureClientSecretSecret"
        objectType: "secretsmanager"
        objectAlias: "azure-client-secret"
      - objectName: "AzureTenantIdSecret"
        objectType: "secretsmanager"
        objectAlias: "azure-tenant-id"
      - objectName: "ALBDnsNameSecret"
        objectType: "secretsmanager"
        objectAlias: "alb-dns-name"
---
# PgAdmin Secret Provider Class (COMMENTED - Not deployed)
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: pgadmin-secrets
#   namespace: pgadmin-stack
# spec:
#   provider: aws
#   parameters:
#     region: eu-central-1
#     objects: |
#       - objectName: "PgAdminEmailSecret"
#         objectType: "secretsmanager"
#         objectAlias: "email"
#       - objectName: "PgAdminPasswordSecret"
#         objectType: "secretsmanager"
#         objectAlias: "password"